### ISSUE TITLE
[Design] (Static) Member design

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/ISADotNet#111]
- Member with capital letter, optional parameters and `[<NamedParams(n)>]` attibute. 

  Example: `table.AddColumn(arg1,arg2,?arg3)`
- Static member with curried parameters and lower case first letter. 
  
  Example: `addColumn (arg1) (arg2) (arg3 option) (table)`
- To avoid to many option arguments, we offer purpose oriented alternative static members. These alternatives must be implemented for members and static members.
  
  Example: `addColumn` is split into:
  -  `appendColumn` 
  -  `insertColumn`, with index
  -  `appendColumnForced`, with forced unique column replacement
  -  `insertColumnForced`, with forced unique column replacement
  -  plus one member for each (`AppendColumn(arg1,arg2)`,`InsertColumn(arg1,arg2,index)`).

@kMutagene @HLWeil @muehlhaus

**Comment by HLWeil** [comment]
Convenience layer: 
```fsharp
addColumn (arg1,arg2,?arg3) : (table -> table)
```
usage:

```fsharp
myTable
|> addColumn(arg1,arg2)
```

**Comment by HLWeil** [comment]
General rule:
`Base functions` should have no optional parameters, as they are the atomic actions which perform one action. 

`Convenience functions` then combine these base functions and can have optional parameters by which they decide which base function to call.
