### ISSUE TITLE
[Design] Mutability

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/ISADotNet#112]
In accordance with possible expectations (based on libraries like Deedle):

 - `members` could transform the input table (mutable)
 - `static members` could output a new table with the changes made (i.e. first call a `Copy()` and then call the member on the new table)

This could potentially boost performance for GUI tools reactively working on the tables

@kMutagene @HLWeil @muehlhaus

**Comment by HLWeil** [comment]
Agree, exactly as stated 👍
