### ISSUE TITLE
[Feature Request] IO implementation for FsSpreadsheet DTO

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/ISADotNet#122]
Related: https://github.com/CSBiology/FsSpreadsheet/issues/30

We need to update **only** ISA changes, without touching any other user content. Therefore we must establish a system to handle this.

For `UPDATE` contracts we MUST pass all `Tables` and the metadata sheet. Any table not passed MUST be deleted, any table passed MUST be updated if changed. The metadata sheet passed MUST be updated if changed.

The exact replacement/update of tables MUST be handled/implemented by the specific IO arctrl implementation.

**Comment by HLWeil** [comment]
Duplicate with #107 ? @Freymaurer
