### ISSUE TITLE
[Feature Request] Remove "leftover" fields from isa-json types

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/ISADotNet#124]
I just found the following in `ISA.Spreadsheet/InvestigationFile/Study.fs`

![image](https://github.com/nfdi4plants/ISADotNet/assets/39732517/6a732de5-46e9-4cb3-8d23-bebb0dd7124b)

If i understand this correctly the fields `CharacteristicCategories` and `UnitCategories` are never set, as the information is contained in `ArcTables?`.

If this is correct, we should remove these fields and similiar cases from the `ArcIsa` types.

@HLWeil

**Comment by HLWeil** [comment]
Hey, this is already a thing in original isa-json. These top-level fields are used to list the distinct respective objects. Then you can just reference them at the appropriate places (e.g. in the processes) usin json-ld identifiers (`@id`).  It's kind of like a registry. 

Not sure whether we need it in the datamodel as the fields could just be filled when parsing to json.

**Comment by Freymaurer** [comment]
> Not sure whether we need it in the datamodel as the fields could just be filled when parsing to json.

Yes, this is exactly what i meant 😅

**Comment by HLWeil** [comment]
Ik, just wanted to state that this is in principle not a leftover from a datamodel port 😅 

You can go ahead and remove these fields IMO, as long as they are not also part of ISA-Tab.

**Comment by Freymaurer** [comment]
Sorry i think i don't get the details. 

Please tell me where i go wrong.

1. The fields i mentioned are represented in ArcTable
2. In ISA-JSON we need these fields, because that is the only place where the information can be found.
3. So we can remove them in ArcAssay/ArcStudy?

**Comment by Freymaurer** [comment]
Removed!
