### ISSUE TITLE
[BUG] Bump FsSpreadsheet dependency to 3.0.0 due to empty FsRows

### ISSUE THREAD

**Issue by omaus** [nfdi4plants/ISADotNet#129]
**Describe the bug**
In FsSpreadsheet NuGet versions <2.0.1, when using `FsWorkbook.fromXlsxFile`, resulting rows in the worksheets are empty. 

**Additional context**
This is fixed in ≥2.0.1 but 2.0.1 and 2.0.2 are delisted due to dependency errors. Therefore, dependencies need to be updated asap to new version 3.0.0.

**Comment by HLWeil** [comment]
This is done, right? @Freymaurer @omaus

**Comment by Freymaurer** [comment]
@omaus

**Comment by omaus** [comment]
Is ISA.NET.XLSX excluded atm.? (since it is not in the .sln file)

If so, why raise the FsSpreadsheet dependency?

**Comment by Freymaurer** [comment]
@omaus you have to look at the arctrl branch 😉

**Comment by omaus** [comment]
> @omaus you have to look at the arctrl branch 😉

🤦‍♂️

---

Okay, I didn't find any FsSpreadsheet.ExcelIO references in the project files on that branch, only such to FsSpreadsheet alone. I bumped them to v3.1.1. I would push that commit to this branch. Is this ok? @Freymaurer @HLWeil
