### ISSUE TITLE
[Feature Request] Quality of life

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/ISADotNet#24]
- Change `Create` static methods to optional parameters

- Adjust naming: `GetNameAsString` should be changed to `GetName`, as name is already a string

- For consistency, change methods to static methods

**Comment by HLWeil** [comment]
- For FactorValue, MaterialAttributeValue, ProcessPArameterValue: GetValue, GetValueWithUnit
- For OntologyAnnotation, Factor, MaterialAttribute, ProcessParameter:  FromString, FromStringWithNumber
- For OntologyAnnotation, Factor, MaterialAttribute, ProcessParameter, FactorValue, MaterialAttributeValue, ProcessPArameterValue: GetName, GetNameWithNumber

**Comment by Freymaurer** [comment]
Please check `For OntologyAnnotation, Factor, MaterialAttribute, ProcessParameter: FromString, FromStringWithNumber` if it is implemented as intendet. In addition i was not able to find the related `ProcessParameter` part.

- Check if [this](https://github.com/nfdi4plants/ISADotNet/blob/QualityOfLife/src/ISADotnet/DataModel/Factor.fs#L48) was implemented correctly
