### ISSUE TITLE
[Suggestion] Unify Assay and Assays namespaces

### ISSUE THREAD

**Issue by kMutagene** [nfdi4plants/ISADotNet#26]
It took me very long to find that you cannot write a single Assay via something like `Assay.write`. Instead, even when only writing a single Assay file, this seems to be necessary:

```fsharp
open ISADotNet.XLSX

[Assay.empty]
|> Assays.write ...

```

Also this seems not be be the function that just writes a assay.xlsx file is it? does something like that exist?

So what i am looking for is something like `Investigation.toFile` for a single Assay. Can this be done currently?

I would also suggest to drop the s from `Assays` to provide a more unified API accross IsaDotNet and IsaDotNet.XLSX

**Comment by HLWeil** [comment]
> Also this seems not be be the function that just writes a assay.xlsx file is it? does something like that exist?

Currently `assay xlsx` files can only be read and not yet written. (Reading and writing as json is possible though)

> So what i am looking for is something like Investigation.toFile for a single Assay. Can this be done currently?

The `Assays.write` could in theory be used to write a single assay in the `ISATab investigation file format`. For this just a little adjustment would be necessary. I'm not sure if this makes sense though, as assays written in this format only really make sense in the context of the investigation file.
The namespace/module naming should be made more concise to better reflect this distinction.

> I would also suggest to drop the s from Assays to provide a more unified API accross IsaDotNet and IsaDotNet.XLSX

As the function mentioned is in the context of the investigation file, I used the namings of the [format specification](https://isa-specs.readthedocs.io/en/latest/isatab.html#investigation-file):

![image](https://user-images.githubusercontent.com/17880410/130420539-60a78f80-387f-4418-aa53-9fae9aff2aa0.png)

---------------------------------------------------

I suggest 2 improvements:

- [ ] Add an `Assay.xlsx` writer
- [ ] Improve module naming to better reflect distinction between `Assay.xlsx` and `Investigation.xlsx` IO functions

What do you think?
