### ISSUE TITLE
[BUG] ISADotNet reference

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/ISADotNet#3]
When referencing ISADotNet like this `#r "nuget: ISADotNet"` in a .fsx i get the following error:

![image](https://user-images.githubusercontent.com/39732517/105335808-cb7d9280-5bd8-11eb-9ffb-16cea06d156e.png)

This might be due to dependencies without fixed minimum version.

**Comment by HLWeil** [comment]
Hey I added a minimum version requirement in 23615a2443769b722db1fccbf44660632941142f. This is included in the nuget package version `0.0.2`. Let me know if it worked out
