### ISSUE TITLE
Worksheet name parsing from assay to CommonAPI rowMajor mistake

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/ISADotNet#34]
I translated one of the existing Swate templates to the new preview format and used the new common api row major format with it.
In Assay the worksheet name was correct, but after parsing to RowWiseSheet it was wrong as `1SPL01_plants` was changed to `1SPL01`.

The problem lies in https://github.com/nfdi4plants/ISADotNet/blob/AssayFileIO/src/ISADotnet/JsonIO/AssayCommonAPI.fs#L98 .

I am currently working on two different versions of a fix.

**Comment by HLWeil** [comment]
Hey, good catch. That's a really unnecessary mistake on my side.
Grouping should just be done by the protocol name. 
Something like:
```fsharp
|> List.groupBy (fun x -> x.ExecutesProtocol. Value.Name. Value)
```
