### ISSUE TITLE
Trim() alle values

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/ISADotNet#37]
It is very easy to add accidental whitespaces to any cells in excel.

These are then parsed as existing values. Add `.Trim()` to all value access functions to remove these issues.

__Reproduce__

1. Open any tableBody cell from a swate table and add  ` ` (whitespace) to it.
2. Parse to Assay or CommonAPI rowMajor format
3. In JSON Value can be found as  `" "`

__Expected behaviour__

1. If only whitespace exists as cell value don't count it as value
2. .Trim() added to all value parsers (header, unit, cell value) will take care of this issue.

**Comment by HLWeil** [comment]
Under the condition that whitespace at the end or beginning of a cell should always be filtered out (which I think is the case), one could just add this to [this line](https://github.com/nfdi4plants/ISADotNet/blob/23a3c33256843b0f28e0f8a885808e2dc55ef121/src/ISADotNet.XLSX/CollectionAux.fs#L107). 

This would then apply for all values, units and annotations inside the excel table (not the header).
