### ISSUE TITLE
Update function not working for record in record

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/ISADotNet#4]
# Problem
When updating one record type with another using the methods in `API.Update`, even when using the `UpdateByExisting` option, a field with a filled record is replaced by a record where no value is set.

An example for this is the `Measurementtype` field of the `Assay` type

# Solution

There should be a way to detect empty records and ignore them. Possibly using an `option` for records in records

**Comment by Freymaurer** [comment]
This is actually by design, as i found it to exhausting to check for all types inside the record type again and then only update it if it contains a new value. So record types will always be replaced. 

> Possibly using an option for records in records

If you define the field as `Measurementtype option` this will work already.

**Comment by HLWeil** [comment]
Yes I thought so, and that's fine. Checking the record recursively kind of imposes a new batch of assumptions, which might not be quite transparent when applying the function.

Nice to hear though that the `option` case is already covered.
