### ISSUE TITLE
[Feature Request] Add `Value.toOptions` as member.

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/ISADotNet#42]
The `toOptions` function [here](https://github.com/nfdi4plants/ISADotNet/blob/2a56e71e2dd6cc91a588dcf448ddb0d63fdbe3ce/src/ISADotnet/DataModel/Factor.fs#L100) is really nice to have. It should not only exist as static member but also as `member this.toOptions` to improve discoverability.

**Comment by HLWeil** [comment]
Closed this, as the API has drastically changed anyways. Feel free to reopen if necessary.
