### ISSUE TITLE
[BUG] Assay: Headers with strange characters are not parsable

### ISSUE THREAD

**Issue by omaus** [nfdi4plants/ISADotNet#56]
**Describe the bug**
If an Assay consists of headers (regardless whether Parameter, Factor, or Characteristic) which contains unusual characters (namely `(` or `[`) the column cannot be parsed.

**To Reproduce**
1. Create Assay with column headers `hello (world)` and `hello [world]`
2. Try parse with common ISA.NET functions
3. See error

**Expected behavior**
Either
- parse correctly, or
- throw error or warning that the respective column cannot be parsed

**Comment by muehlhaus** [comment]
The expected behavior should be to parse the term between '[]' including all characters. NO warning or exception. We want to separate checking potential rules (e.g. ARC, ISA, ...) from parsing and managment whenever possible...
