### ISSUE TITLE
[Feature Request] Protocol Columns

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/ISADotNet#61]
**Is your feature request related to a problem? Please describe.**
Assay and Study xlsx files will soon be containing more columns describing the underlying protocol. These will be:
- `Protocol Type` (+ `Term Source REF` and `Term Accession Number`)
- `Protocol REF`
- `Protocol Description`
- `Protocol URI`
- `Protocol Version`

**Describe the solution you'd like**
Assay (and Study) xlsx file writers should be able to handle these new columns.

**References**
https://github.com/nfdi4plants/Swate/issues/207
https://github.com/nfdi4plants/nfdi4plants_ontology/issues/32

**Comment by Freymaurer** [comment]
https://github.com/nfdi4plants/Swate/issues/212

`Protocol REF` und `Protocol Type` sind implementiert.

![image](https://user-images.githubusercontent.com/39732517/179976628-cab99618-1d03-40a7-a457-ff6a1b7dee8d.png)
