### ISSUE TITLE
[Feature Request] Move API functions from SWATE into ISA

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/ISADotNet#98]
- [x] appendCompositeColumn (CompositeHeader -> CompositeCell [] option -> ArcTable -> ArcTable)
- [x] insertCompositeColumn (CompositeHeader -> CompositeCell [] option -> int -> ArcTable -> ArcTable)
- [x] insertCompositeColumns
- [x] getColumn
- [x] setCompositeHeader
- [x] setCompositeCell (CompositeCell -> int -> int -> ArcTable -> ArcTable)
- [x] ~~setCompositeCells~~
- [x] setCompositeColumn
- [x] removeColumn
- [x] removeRow
- [x] addRow
- [x] validateTable

**Comment by Freymaurer** [comment]
- [ ] deprecation functions
- [ ] CompositeHeader.ofString function

**Comment by Freymaurer** [comment]
`insertCompositeColumn` must do:
- [ ] ensure unique header
- [ ] ensure unique non term columns

**Comment by Freymaurer** [comment]
This will be a shitty example, because i always forget the right one:

`Component [Peptidase]` could be used multiple times in the same assay/table. Do we manage unique header names in ArcTable or must Swate do this to be excel conform?
